CFLAGS=-Wall -Wno-missing-braces

all: datstrings datrelt datbody

datstrings: datstrings.c
	$(CC) $(CFLAGS) datstrings.c -o datstrings

datrelt: datrelt.c
	$(CC) $(CFLAGS) datrelt.c -o datrelt

datbody: datbody.c
	$(CC) $(CFLAGS) datbody.c -o datbody
